/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        flux: {
          surface: '#faf8ff',
          'surface-dim': '#d2d9f4',
          'surface-bright': '#faf8ff',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#f2f3ff',
          'surface-container': '#eaedff',
          'surface-container-high': '#e2e7ff',
          'surface-container-highest': '#dae2fd',
          'on-surface': '#131b2e',
          'on-surface-variant': '#434656',
          'inverse-surface': '#283044',
          'inverse-on-surface': '#eef0ff',
          outline: '#737688',
          'outline-variant': '#c3c5d9',
          'surface-tint': '#004ced',
          primary: '#003ec7',
          'on-primary': '#ffffff',
          'primary-container': '#0052ff',
          'on-primary-container': '#dfe3ff',
          'inverse-primary': '#b7c4ff',
          secondary: '#006685',
          'on-secondary': '#ffffff',
          'secondary-container': '#79d4fe',
          'on-secondary-container': '#005b77',
          tertiary: '#661bc5',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#7f3ede',
          'on-tertiary-container': '#eedfff',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          'primary-fixed': '#dde1ff',
          'primary-fixed-dim': '#b7c4ff',
          'on-primary-fixed': '#001452',
          'on-primary-fixed-variant': '#0038b6',
          'secondary-fixed': '#bfe9ff',
          'secondary-fixed-dim': '#76d2fb',
          'on-secondary-fixed': '#001f2a',
          'on-secondary-fixed-variant': '#004d65',
          'tertiary-fixed': '#ecdcff',
          'tertiary-fixed-dim': '#d5baff',
          'on-tertiary-fixed': '#270057',
          'on-tertiary-fixed-variant': '#5e08bd',
          background: '#faf8ff',
          'on-background': '#131b2e',
          'surface-variant': '#dae2fd',
        },
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
        mono: ["'Geist Mono'", "monospace"],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        float: "0 4px 12px 0 rgba(19, 27, 46, 0.05)",
      },
    },
  },
  plugins: [],
};
